### ISSUE TITLE
react-native can't use View as texture

### ISSUE THREAD

**Issue by macrozone** [gre/gl-react#160]
### bug report

I try to adopt https://github.com/miklosme/gl-react-color-blending to gl-react version 3. 

#### library version

gl-react-expo@3.13.0

gl-react@3.13.0

#### Expected behavior

I can use arbitrary react-native views as texture

#### Actual behavior

I get a warning: "uniform children: child is not renderable. Got: null"

#### Steps to reproduce the behavior

```

const ColorBlendingShader = ({ children, color, blendMode = 'blendAdd' }) => (
  <Node
    shader={shaders[blendMode]}
    uniforms={{
      children,
      color,
    }}
  />
)
const ColorBlendingExample = () => (
  <Surface
    style={{
      width: 300,
      height: 300,
    }}
  >
    <ColorBlendingShader color={[0.1, 0.9, 0.1, 1]} blendMode="blendMultiply">
      <View><Text>Hello world</Text></View>
    </ColorBlendingShader>
  </Surface>
)
```

**Comment by gre** [comment]
thanks for the issue.

This is unfortunately not yet supported. The good news is there is a workaround possible: if you rasterize your view first with something like `react-native-view-shot` and inject the url as a texture yourself.

Hopefully with the recent lib `react-native-webgl-view-shot`, this will be possible to write such thing, but I have not yet figured out how this will transparently work (like maybe you would need to wrap a `<Rasterize>` to make this less implicit – rasterizing have some costs)

i'm closing this issue because this is planned by https://github.com/gre/gl-react/issues/145 already ;)
