### ISSUE TITLE
Debugging: disable RNWebGL

### ISSUE THREAD

**Issue by stoffern** [gre/gl-react#162]
@gre 

Android
Sorry for making a issue of this but it is needed for other people and in docs 😉 

Is there a way to disable  the use of `RNWebGL` in the Surface or other without removing the library for debugging purposes?

**Comment by gre** [comment]
disabling RNWebGL without removing the library 🤔 I don't understand

**Comment by stoffern** [comment]
is it possible to run gl-react on react native without the `RNWebGL` lib?

if so it would be nice to have the feature to disable the library in order to run remote debugging 😉

**Comment by gre** [comment]
no it is not possible. RNWebGL is the WebGL native implementation on top of OpenGL. how would it work otherwise?
this implementation used to be in gl-react-native but it was just externalized to react-native-webgl so gl-react-native don't actually have native code and can focus on just hooking gl-react to react-native-webgl.

hope it does make sense.

for the remote debugging issue, we probably should raise on issue on https://github.com/react-community/react-native-webgl/issues and try to find solutions for this.

**Comment by stoffern** [comment]
Great, thanks for the clarification. 👍
