### ISSUE TITLE
Unnecessary span tag?

### ISSUE THREAD

**Issue by rockmandash** [gre/gl-react#184]
Hello, first of all, thanks for this wonderful library.
This library is so killed.
But I wonder there is a lot of span tags out there.
Is there any particular reason?
Can we replace it with fragment?
Thank you very much.

**Comment by gre** [comment]
Yeah maybe we can replace with Fragment. this is historic reason before fragment existed.
The usecase is legit because basically you are allowed to have DOM element inside GL components and they need to be mounted somewhere.. in dom implementation, i figured out we can put the DOM straight inside the `<canvas>`, it works & just don't display anywhere which is exactly what I needed. 
 (examples https://gl-react-cookbook.surge.sh/textfunky | https://gl-react-cookbook.surge.sh/video ...)

Another interesting fact is that, since the DOM exists, you can actually inspect with React inspector and see the stack of components. If it is still the case for `React.Fragment` then we could probably migrate all the spans to it.

**Comment by rockmandash** [comment]
Thank you for your reply.
