### ISSUE TITLE
Animations seems to cap at 30FPS, requestAnimationFrame

### ISSUE THREAD

**Issue by morukutsu** [gre/gl-react#61]
Hi. I'm working on animations with gl-react (by updating uniforms every frame).
To do so, I trigger a react setState every time requestAnimationFrame calls back.
However, I quickly noticed the animations are not smooth. I'm using gl-react-dom.

Here is what the Chrome timeline shows:
![image](https://cloud.githubusercontent.com/assets/2243831/14426646/b02c46b4-fff0-11e5-9e81-3a43661096fd.png)

I would expect the frame to be presented on the screen directly after the rendering is finished. However, it seems that only 1 frame is presented every two frames.

I observe a similar behaviour with this demo: http://projectseptemberinc.github.io/gl-react-dom/Examples/Video/

Meanwhile, a random webgl demo I googled renders at 60FPS: http://www.solointeractivestudio.com/
![image](https://cloud.githubusercontent.com/assets/2243831/14426770/4aa005a0-fff1-11e5-87df-29a2b105948e.png)

I built a similar Square shader with Shadertoy and it is smooth: https://www.shadertoy.com/view/XstSz2

I did not dig a lot into the gl-react-dom source yet but it seems there is an issue and I can't find the cause.
Do you have an idea? Thanks :+1: 

My first guess (by looking at the timelines) is that handleDraw() is only called once every two frames (in the video example).

Here is my code example (bit rough, it's wip): 

``` javascript
export default class LoginPage extends React.Component {
    constructor() {
        super();
        this.update = this.update.bind(this);
    }

    componentWillMount() {
        this.square = new SquareCore();
        this.update();
    }

    update() {
        this.square.tick(0.016);

        this.raf = window.requestAnimationFrame(this.update);

        // Trigger render
        this.setState({ dummy: 1 });
    }

    componentWillUnmount () {
        cancelAnimationFrame(this.raf);
    }

    render() {
        return (
            <div className={styles.content}>
                <Surface width={511} height={341}>
                    <SquareDisplay state={this.square.getState() }/>
                </Surface>
            </div>
        );
    }
}
```

``` GLSL
const shaders = GL.Shaders.create({
    shader: {
        frag: `
        precision highp float;
        varying vec2 uv;
        uniform vec4 squareColor;
        uniform vec2 resolution;
        uniform float posX, posY, squareW, squareH, time;
        void main () {
            // Compute fragment position without aspect ratio normalization
            vec2 fragCoord = vec2(gl_FragCoord.x, gl_FragCoord.y);
            vec2 fragPos = vec2(1.0 / resolution.x, 1.0 / resolution.x);
            fragPos = fragPos * fragCoord;
            fragPos.y += ((resolution.x - resolution.y) / 2.0) / resolution.x;

            float posX2 = posX + sin(time);

            vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
            if (fragPos.x > posX2            &&
                fragPos.x <= posX2 + squareW &&
                fragPos.y > posY            &&
                fragPos.y <= posY + squareH
            )
            {
                color = squareColor;
            }
            gl_FragColor = color;
        }`
    }
});
```

**Comment by morukutsu** [comment]
I was digging this a bit and I can add some informations, the problem is in GLCanvas.js.
https://github.com/ProjectSeptemberInc/gl-react-dom/blob/master/src/GLCanvas.js

1. componentWillReceiveProps() calls _requestSyncData()

2. _requestSyncData() calls _requestDraw()

3. _requestDraw() checks if _rafDraw() is valid, if not, schedule rendering for the next frame. If yes, skips.

4. At the next raf, _handleDraw cleans the raf handle and draws the frame.

Once every two frames, when I set the props in my code with my own requestAnimationFrame, this flow will be called while a rendering is scheduled in GLCanvas. Thus, skipping a frame and capping the refresh rate at 30FPS.

My quick workaround was to ignore the internal requestAnimationFrame because I use my own. My guess is, if the autoRedraw is not set, GLCanvas should not use rafDraw at all?

Workaround:
``` javascript
  _requestDraw () {
    /*if (this._rafDraw) return;
      this._rafDraw = raf(this._handleDraw);*/
      this._handleDraw();
  }
```

Still thinking about the right fix :)

**Comment by gre** [comment]
good catch.

Here is the reason of current behavior:
I had to do this is because of specific use-case where you need to use a library like react-canvas. Because react-canvas will render the canvas into next tick too, so I need to wait it to be ready one more tick so we don't inject a texture that contains the previous version of that canvas.

> If you want to look at this case, we have an example in Simple examples, where you can change a text and the redraw happens after each input change (not continuously).

But your bug is true and we need to fix it, maybe I need to introduce a prop called "doubleBuffering" that make the current behavior, and default behavior would be to not wait one tick everytime?

Now a solution to your problem is probably to use **"autoRedraw"** prop (on Surface), I think it should prevent gl-react to behave like this.
**^ maybe this is actually the answer to this bug?**

**Comment by morukutsu** [comment]
I see, it makes sense. My suggestion is that only one agent should call requestAnimationFrame and this call should triggers all renders.

For example, I just checked the react-canvas source code. After react-canvas Surface mount, it starts scheduling a draw every frame. It works well that way because it is self contained. However, when gl-react is added on top of that (which also schedules drawing), there is an issue and I understand your fix.

But in this case I can suggest another: I currently see no issue in **totally bypassing react-canvas scheduling**, and actually force react-canvas's surface to update juste before gl-react, in the same frame. Doing so simplify the logic, and no frame of lag is introduced. But it involves modifications in the react-canvas code base which is an issue.

About the autoRedraw suggestion, I tried but it doesn't work in my use case, as far as I know.
In my code, the requestAnimationFrame updates values (positions, sizes, colors...) on the JS side for each component, which are then read during the main component render method. Those values are given to shader uniforms during the render execution. My understanding is that Surface's autoRedraw works well when a child component updates itself.

Here is my use case (stacking effects):
```javascript
render() {
        return (
            <div className={styles.content}>
                <Surface width={511} height={341}>
                    <StrobeDisplay state={this.strobe.getState() }>
                        <ImageDisplay state={this.image.getState() }/>
                    </StrobeDisplay>
                </Surface>
            </div>
        );
    }
```
In this case, if I enable autoRedraw, the pixel shader will be displayed every frame but always with the same uniforms since render() would be called only once. I could probably use ref to the underlying GL.Node to manually update the uniforms ? But I don't know, it complicates the logic.

**Comment by gre** [comment]
so you suggest we should have a way to force the rendering to happen on current frame instead of scheduling, maybe this should be introduced as prop in both gl-react-* and react-canvas.
The only issue I may have is that, using a "schedule to next frame" approach allow to easily "dedup" the multiple render calls issue. I mean that, multiple people can do a "requestRender" , but at the end it will happen once, after everyone have done his job. I'm not sure how easy to move away from this.

Or maybe this: if you enable this "dontSchedule" mecanism, then **you are responsible** of calling the draw method at the appropriate time?

Maybe this could work, one of the biggest problem of react-canvas is that it's mostly dead these days.. but we could fork it to check if this idea would work.

**Comment by morukutsu** [comment]
Yep, I think for most of the use cases, the current behaviour is fine. 

> Or maybe this: if you enable this "dontSchedule" mecanism, then you are responsible of calling the draw method at the appropriate time?
Exactly, the idea is to mimic react: calling setState or setting the props triggers the render.

In gl-react-dom, I obtained a dontSchedule behaviour by just calling _handleDraw everytime props are set.

In react-canvas, with dontSchedule on, in https://github.com/Flipboard/react-canvas/blob/master/lib/Surface.js. componentDidUpdate should not call this.node.draw().
Then, Surface should expose a function doing:
``` javascript
this.clear();
this.draw();
```

Then gl-react could trigger this function whenever it needs the canvas to be updated.
I did not tested that but I think it can work, I will do a demo.

**Comment by gre** [comment]
ok thanks

**Comment by gre** [comment]
This is now solved in gl-react v3 ! It's a complete rewrite.
- see release article: http://greweb.me/2016/12/gl-react-v3/
- see cookbook/api: https://gl-react-cookbook.surge.sh
- gl-react v3 is still in development. (hosted on: http://github.com/gre/gl-react )
- gl-react v2 is still the stable version (hosted on: https://github.com/ProjectSeptemberInc/gl-react )


How this issue is solved: explained in the article in how the redraw(), flush() system works. Surface runs a raf loop that will flush() at 60 fps.
