### ISSUE TITLE
add support to array of sampler2D

### ISSUE THREAD

**Issue by gullitmiranda** [gre/gl-react#68]
I'm trying to use an array of sampler2D, but unfortunately I get the following error:

```
Shader 'canvas': uniform 'pictures' at index 0, Unrecognized object: '[object Object]'
```

js:

``` js
  const sources = [{uri: '...'}, {uri: '...'}]; //
  const pictures = sources.map((source) => resolveAssetSource(source)); 

     glCanvas = (
        <Surface
          ref="glCanvas"
          width={width}
          height={height}
        >
          <GL.Node
            shader={shaders.canvas}
            uniforms={{
              resolution,
              picturesLength: pictures.length,
              pictures,
            }}
          />
        </Surface>
      );
```

ps, I'm using gl-react@2.2.8 and gl-react-native@2.33.0

**Comment by gre** [comment]
Can I know the usecase of this?
This is not so easy to to implement (for a few reason) **but** I'll try to cover it in my current lib refactoring.
Note that in GLSL version 110 you can't for-loop on a dynamic variable, it must be constant, is your texture array constant?

**Comment by gullitmiranda** [comment]
I need to render a list of textures to compile in a single image. 
They can be constants since the rendering of opengl is only to generate a final image.

**Comment by gre** [comment]
This is now solved in gl-react v3 ! It's a complete rewrite.
- see release article: http://greweb.me/2016/12/gl-react-v3/
- see cookbook/api: https://gl-react-cookbook.surge.sh
- gl-react v3 is still in development. (hosted on: http://github.com/gre/gl-react )
- gl-react v2 is still the stable version (hosted on: https://github.com/ProjectSeptemberInc/gl-react )


Relevant example that show this issue is fixed: https://gl-react-cookbook.surge.sh/mergechannels and https://gl-react-cookbook.surge.sh/mergechannelsfun
