### ISSUE TITLE
[NPM] better publish and docs

### ISSUE THREAD

**Issue by stoffern** [gre/gl-react#79]
### *feature request*
Please concider using `semantic-release` and `commitizen`
For automatic documentation, versioning and npm releasing.

More info here:
https://github.com/semantic-release/semantic-release
https://github.com/commitizen/cz-cli

**Comment by gre** [comment]
I didn't know this, sounds interesting. I somehow have my own scripts at the moment.

This repository is a multi-repo that contains multiple projects (I've inspired from structure like in babel or flow, it makes it easier to manage the code and do generic "building scripts" so each packages don't dep on any devDeps but only the top project bring the devDeps,..),
anyway, do you know if these tools know how to handle that?

For the publish process, i'm a bit less sure, but my current idea was I would release each new version of gl-react / gl-react-dom / gl-react-native with the same version (e.g. 3.1.0 for all..). That way, when you look at the repo / for a given version, all is consistant, and it's easy to know which version will work with which. No idea if it's the best idea (what I see is some packages version might have no code changes because for instance, had to release a new patch for gl-react-native – RN tends to evolve fastly, and can have breaking changes).


As for documentation, I already have automated doc, each time I build the project, it generate cookbook/API.json, that is rendered here: https://gl-react-cookbook.surge.sh/api . Is there something better we can do?

**Comment by gre** [comment]
one think i'll probably need to setup is CI for tests. I'm not sure what CI is the best for current tests as it needs to have OpenGL ( https://github.com/stackgl/headless-gl#system-dependencies )

Is there points i'm missing from the tools you suggested that I don't support?

**Comment by stoffern** [comment]
Well first of all i dont think that releasing same versions for all gl-react libs at the same time is a good idea.
It will generate alot of job when you release a small independent fix in one library.
This should be set by dependencies, so if you have a "breaking change" in gl-react then release a fix for this in gl-react-native and set the dependency for this.
This is what `react` and `react-native` is doing right now.

Using commitizen will give you a command `git cz` instead of `git commit`.
You will get a graphical menu asking you what change this is? (new feature, bug fix, docs, performance etc..) You will also need to describe the change in step 2. and in step 4. it asks you if it is a Breaking change?..

Depending on all this from commitizen and if the CI checks succeeds, semantic-release will automaticly generate a new version, release details, and publish the new version to NPM for you automaticly.

Angular and alot of other repos use this as a standard and Github is working on integrating this as a standardization for releases.

**Comment by stoffern** [comment]
new features = 1.0.0 version
bugfix = 0.1.0 version
performance etc is 0.0.1 versioning

For bigger og releases that should be put together with many commits you should create a new branch for this release. and when it is merged into master, semantic will automaticly create a release log for all commits, generate version, and publish it to NPM.
Changelog file can also be generated with semantic.

I use semantic release here:
https://github.com/stoffern/react-native-image-cropper

**Comment by gre** [comment]
maybe this could be interesting too: https://github.com/lerna/lerna used by babel ( saw the mention in https://babeljs.io/blog/2016/12/07/the-state-of-babel )

**Comment by stoffern** [comment]
Facebook tried to keep same version numbers, but it all failed when they had a breaking change in react and could not match it in time with react-native. They stoped doing it after that.

I still think that keeping version numbers between repos will be pretty hard to do in the long run.
As i wrote in my last 2 posts.

Lets say you release a bugfix in `gl-react-native` that fixes issues related to Android. Causing a new release: 12.1.2 -> 12.2.0. Then you need to release a blank version for `gl-react-dom`. the "web" people will ask, what is fixed in this version?

I think version numbering, keeping version notes, and change log is a big deal.
Breaking changes occours, and will then automaticly be updated. Depending packages will also be set in peerDeps as of nodejs 6.

**Comment by gre** [comment]
the project is now using lerna, good enough for now. I want to stabilize that state a bit before going forward (i still have a hack to workaround issue with symlink & also i had to put gl-react in a devDep of some packages because the peerDep wouldn't install it.. (FYI it's a progress, it was even more hacky before^^) )

the granularity of releases can be improved later, in fact lerna allows to chose between fixed/locked mode or independent. (there is even `lerna-semantic-release` if we need more)
